### PR TITLE
Simplify command to verify content of aevolume

### PR DESCRIPTION
**Pull request by NVolcz**

### CODE REVIEW

**Comment by zhill** [comment]
@NVolcz thanks. I can merge this once you sign-off the commit with the DCO (using git commit -s). You can just force-push your branch again and that should get the DCO check to pass.

**Comment by NVolcz** [comment]
What do you think of updating the other code examples which starts with `cd ~/aevolume`? Some of them could also be simplied but I get the feeling that there was a reason for starting every code block that way.

**Comment by zhill** [comment]
> starting

Generally, it was a way to make clear that all config/anchore stuff is in a specific and isolated directory. There may be a clearer way to indicate that, and it isn't as important now that we use mechanisms like docker's own volume config instead of bind-mounting directories for config and db.

**Comment by zhill** [comment]
Realized this didn't get merged. @NVolcz if you can add the DCO sign-off then I can merge it. Thanks.

**Comment by zhill** [comment]
Thanks! Sorry it took a while to get merged. It is appreciated!

**Pull request merged**
