### PR TITLE
Fixes spelling error and carries the same example to the yaml

### PR DESCRIPTION
**Pull request by signed8bit**

### CODE REVIEW

**Comment by zhill** [comment]
@signed8bit can you please sign the commit (git commit -s --amend) and force-push your branch again? That should pass the DCO check.

**Comment by signed8bit** [comment]
@zhill Done!

**Comment by signed8bit** [comment]
Already addressed in https://github.com/anchore/enterprise-docs/commit/eb060b2dee665aed16a4465003a9e135c48da56f

**Comment by signed8bit** [comment]
I take that back, looks like @nurmi fixed the same typo in a different file.

**Comment by signed8bit** [comment]
The other instance fixed in https://github.com/anchore/enterprise-docs/commit/9a7b3130f0ae667723f80499069dc6f983d01344

**Pull request closed without merging**
